name: "Terraform Plan and Apply"
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials using OIDC
      uses: dflook/configure-oidc-aws-credentials@v1.0.0
      with:
        role-arn: ${{ secrets.AWS_ROLE_TO_ASSUME }}  # Corrected: Use role-arn
        sts-region: ${{ secrets.AWS_REGION }}        # Corrected: Use sts-region

    # Step : Set up Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve
